version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=mongodb://mongo:27017
      - PORT=5000
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:5000
    depends_on:
      - api
volumes:
  mongo-data:
